repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

#-   repo: https://github.com/PyCQA/isort
#    rev: 5.10.1
#    hooks:
#        - id: isort

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.991'  # Use the sha / tag you want to point at
#    hooks:
#    -   id: mypy
#        args: [--no-strict-optional, --ignore-missing-imports]